obj -m += Q1.c

KDIR = /lib/module/$ (shell uname -r)/ build

all:
	make -c lib/madule/$(shell uname -r)/build M=$(shell pwd) module

clean:
	make -c lib/madule/$(shell uname -r)/build M=$(shell pwd) clean